#!/bin/bash


previous_ip=$(cat /home/martin/Github/vim/Raspberry.ip)
current_ip=$(ifconfig eth0 | grep -A0 global)

if [ "$previous_ip" != "$current_ip" ]
then
	ifconfig eth0 | grep -A0 global  > /home/martin/Github/vim/Raspberry.ip
	test1=${current_ip#*6*}
	test2=${test1%*pre*}
	echo current_ip
	echo test1
	echo test2
        echo "Ist ungleich"
	git status
	git add *
	git status
	git commit -a -m "Added new ip.address"
	git status
	git push
	git status
else
        echo "Ist gleich"
fi
