#!/bin/bash


ifconfig eth0 | grep -A0 global  > /home/martin/Github/vim/Raspberry.ip
echo "hallo" >> /home/martin/Github/vim/Raspberry.ip
git status
git add *
git status
git commit -a -m "Added new ip.address"
git status
git push
MartinTschoepe
Test/1234
