#!/bin/bash

previous_ip=$(cat ./Raspberry.ip)
current_ip=$(ifconfig eth0 | grep -A0 global)
echo $previous_ip
echo $current_ip

if [ "$previous_ip" != "$current_ip" ]
then
	echo "Ist ungleich"
else
	echo "Ist gleich"
fi
echo hallo
